module.exports = {
"c major" 					: "c,d,e,f,g,a,b",
"g. major" 					: "g,a,b,c,d,e,f sharp",
"d major" 					: "d,e,f sharp,g,a,b,c sharp",
"a major" 					: "a,b,c sharp,d,e,f sharp,g sharp",
"e major" 					: "e,f sharp,g sharp,a,b,c sharp,d sharp",
"b. major" 					: "b,c sharp,d sharp,e,f sharp,g sharp,ay sharp",
"f sharp major" 			: "f sharp,g sharp,ay sharp,b,c sharp,d sharp,e sharp",
"c sharp major" 			: "c sharp,d sharp,e sharp,f sharp,g sharp,ay sharp,b sharp",
"f major" 					: "f,g,a,b flat,c,d,e",
"b. flat major" 			: "b flat,c,d,e flat,f,g,a",
"e flat major" 				: "e flat,f,g,ay flat,b flat,c,d",
"a flat major" 				: "ay flat,b flat,c,d flat,e flat,f,g",
"d flat major" 				: "d flat,e flat,f,g flat,ay flat,b flat,c",
"g. flat major" 			: "g flat,ay flat,b flat,c flat,d flat,e flat,f",
"c flat major" 				: "c flat,d flat,e flat,f flat,g flat,ay flat,b flat",
"a natural minor" 			: "a,b,c,d,e,f,g",
"a minor" 					: "a,b,c,d,e,f,g",
"a harmonic minor"			: "a,b,c,d,e,f,g sharp",
"a melodic minor" 			: "a,b,c,d,e,f sharp,g sharp",
"e natural minor" 			: "e,f sharp,g,a,b,c,d",
"e minor" 					: "e,f sharp,g,a,b,c,d",
"e harmonic minor" 			: "e,f sharp,g,a,b,c,d sharp",
"e melodic minor" 			: "e,f sharp,g,a,b,c sharp,d sharp",
"b. natural minor" 			: "b,c sharp,d,e,f sharp,g,a",
"b. minor" 					: "b,c sharp,d,e,f sharp,g,a",
"b. harmonic minor" 		: "b,c sharp,d,e,f sharp,g,ay sharp",
"b. melodic minor" 			: "b,c sharp,d,e,f sharp,g sharp,ay sharp",
"f sharp natural minor" 	: "f sharp,g sharp,a,b,c sharp,d,e",
"f sharp minor" 			: "f sharp,g sharp,a,b,c sharp,d,e",
"f sharp harmonic minor" 	: "f sharp,g sharp,a,b,c sharp,d,e sharp",
"f sharp melodic minor" 	: "f sharp,g sharp,a,b,c sharp,d sharp,e sharp",
"c sharp natural minor" 	: "c sharp,d sharp,e,f sharp,g sharp,a,b",
"c sharp minor" 			: "c sharp,d sharp,e,f sharp,g sharp,a,b",
"c sharp harmonic minor" 	: "c sharp,d sharp,e,f sharp,g sharp,a,b sharp",
"c sharp melodic minor" 	: "c sharp,d sharp,e,f sharp,g sharp,ay sharp,b sharp",
"d natural minor" 			: "d,e,f,g,a,b flat,c",
"d minor" 					: "d,e,f,g,a,b flat,c",
"d harmonic minor" 			: "d,e,f,g,a,b flat,c sharp",
"d melodic minor" 			: "d,e,f,g,a,b,c sharp",
"g. natural minor" 			: "g,a,b flat,c,d,e flat,f",
"g. minor" 					: "g,a,b flat,c,d,e flat,f",
"g. harmonic minor"			: "g,a,b flat,c,d,e flat,f sharp",
"g. melodic minor" 			: "g,a,b flat,c,d,e,f sharp",
"c natural minor" 			: "c,d,e flat,f,g,ay flat,b flat",
"c minor" 					: "c,d,e flat,f,g,ay flat,b flat",
"c harmonic minor" 			: "c,d,e flat,f,g,ay flat,b flat",
"c melodic minor" 			: "c,d,e flat,f,g,a,b",
"f natural minor" 			: "f,g,ay flat,b flat,c,d flat,e flat",
"f minor" 					: "f,g,ay flat,b flat,c,d flat,e flat",
"f harmonic minor" 			: "f,g,ay flat,b flat,c,d flat,e",
"f melodic minor" 			: "f,g,ay flat,b flat,c,d,e"
};
